server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: security
          uri: lb://security
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: finance
          uri: lb://finance
          predicates:
            - Path=/finance/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000/"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
        add-to-simple-url-handler-mapping: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    #sentinel
    sentinel:
      transport:
        dashboard: localhost:9090
      eager: true
