server:
  port: 8090
spring:
  application:
    name: finance
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lilo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create #这个配置表示在程序启动后运行的sql语句会进行更新，而不是在停止程序后删除
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      bindings:
        logSend:
          destination: log
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos